### ISSUE TITLE
Issue: Everything

### ISSUE THREAD

**Issue by Headteachers** [Fraserbc/BetterDiscord-Embeds#13]
I've heard from sources in the past that the owner of this github never responds to issues, may as well be abandoned.

**Comment by iCrashPhones** [comment]
doesnt work, tested today

**Comment by Headteachers** [comment]
we know it's against the tos, that's why we use it..

**Comment by Fraserbc** [comment]
Really sorry guys! I've not logged onto GitHub in a while so I can see why you would think it has been abandoned. I have just pushed changes today that fix it. Download it again and all the issues should be solved. The bug was caused due to discord changing how the text entry works and also the id used for sending messages. Hope it works now and reiterating how sorry I am for not replying for ages

**Comment by ochen1** [comment]
It works now! Thanks so much for this plugin!

**Comment by Fraserbc** [comment]
Thanks for confirming that it's working again! I'm going to close this issue now. You can reopen it if you still have issues
